accounts/urls.py
# Django
from django.urls import path
# Project
from .views import signupView, loginView, logoutView 

app_name = "accounts"

urlpatterns = [
	# Registro de usuario
    path('signup/', signupView, name="signup"),
    path('login', loginView, name="login"),
    path('logout/', logoutView, name="logout"),
]

articles/urls.py
from django.urls import path

from .views import article_list, article_create, article_detail, article_update, article_delete

app_name = "articles"

urlpatterns = [
    path('', article_list, name="list"),
    path('create/', article_create, name="create"),
    path('<int:id>/', article_detail, name="detail"),
    path('<int:id>/update', article_update, name="update"),
    path('<int:id>/delete', article_delete, name="delete"),
]

ninjablog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import about, homepage
# Static files 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name='home'),
    path('about/', about, name='about'),
    path('articles/', include('articles.urls', namespace="articles")),
    path('accounts/', include('accounts.urls', namespace="accounts"))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
# Django
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
	title 	= models.CharField("Titulo",max_length=100)
	slug 	= models.SlugField()
	body	= models.TextField("Contenido")
	date 	= models.DateTimeField("Fecha de creación", auto_now=False, auto_now_add=True)
	updated = models.DateTimeField("Fecha de Actualización",auto_now=True, auto_now_add=False)
	# thumbnail
	Image 	= models.ImageField("Imagen",
			         blank=True,
			         default='cripto.png')
	# Author
	author 	= models.ForeignKey(User, default = None, on_delete=models.CASCADE, verbose_name="Autor")

	class Meta:
		verbose_name = 'Artículo'
		verbose_name_plural = 'Artículos'
	
	def __str__(self):
		return str(self.title)

	# Recortador de texto
	def snippet(self):
		return self.body[:100]+'...'

	# URL del Articulo
	def get_absolute_url(self):
		return reverse("articles:detail", kwargs={"id":self.id})

articles/forms.py
# Django
from django import forms
# Project
from .models import Article

class ArticleForm(forms.ModelForm):
	class Meta:
		model = Article
		fields = ["title", "slug","body", "Image"]

accounts/views.py
# Django
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Registro de usuario
def signupView(request):
	template_name = 'signup.html'
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		# Si el formulario es valido
		if form.is_valid():
			user = form.save()
			login(request, user)
			return redirect("home")
	else:
		form = UserCreationForm()

	context = {
		"form": form,
	}
	return render(request, template_name, context)

# Inicio de Sesion
def loginView(request):
	template_name = 'login.html'
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request, user)
			if "next" in request.POST:
				return redirect(request.POST.get("next"))
			else:
				return redirect("articles:list")
	else:
		form = AuthenticationForm()
	context = {
		"form": form,
	}
	return render(request, template_name, context)

# Cerrar Sesion
def logoutView(request):
	logout(request)
	return redirect("home")

articles/views.py
# Django
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
# Project
from .models import Article
from .forms import ArticleForm

# Lista de Articulos
def article_list(request):
	template_name = 'article_list.html'
	articles = Article.objects.all().order_by("date")
	context = {
		'articles': articles,
	}
	return render(request, template_name, context)

# Crear Articulo
@login_required(login_url='accounts:login')
def article_create(request):
	template_name = 'article_create.html'
	
	form = ArticleForm(request.POST or None, request.FILES or None)
	
	if form.is_valid():
		instance = form.save(commit = False)
		instance.author = request.user
		instance.save()
		try:
			return HttpResponseRedirect(instance.get_absolute_url())
		except:
			return redirect("articles:list")
	context = {
		"title": "Crear Artículo",
		"form": form
	}
	return render(request, template_name, context)

# Detalles de un Articulo
def article_detail(request, id):
	template_name = 'article_detail.html'
	try:
		instance = Article.objects.get(id=id)
	except:
		template_names 	= "404.html"
		detail_comment = "El Artículo que buscas no existe"
		contextdata = {
			"detail_comment": detail_comment,
			}
		return render(request, template_names, contextdata, status = 404)
	context = {
		'article': instance,
	}
	return render(request, template_name, context)

# Actualizar un Articulo
@login_required(login_url='accounts:login')
def article_update(request, id=None):
    template_name = 'article_create.html'
    
    try:
    	instance = Article.objects.get(id=id)
    except:
    	template_names 	= "404.html"
    	detail_comment = "El Artículo que deseas editar no existe"
    	contextdata = {
    		"detail_comment": detail_comment,
    	}
    	return render(request, template_names, contextdata, status = 404)
    # Verificamos que el usuario sea el autor del articulo
    if instance.author != request.user:
    	template_name 	= "403.html"
    	detail_comment = "Opsss!!!"
    	content_text = instance.title
    	contextdata = {
    		"detail_comment": detail_comment,
			"content_text": content_text,
			"userlogin": request.user,
			"editall": True,
		}
    	return render(request, template_name, contextdata, status = 403)
    # Formulario
    form = ArticleForm(request.POST or None, request.FILES or None, instance=instance)
    # Verificamos que el formulario es valido
    if form.is_valid():
    	instance = form.save(commit = False)
    	instance.save()
    	return redirect("articles:detail", id=id)
    # Contexto
    context = {
    	"title":'Actualizar Artículo',
    	"articles": instance,
    	"form": form
    }
    return render(request, template_name, context)

# Eliminar Articulo
@login_required(login_url='accounts:login')
def article_delete(request, id=None):
	try:
		instance = Article.objects.get(id=id)
	except:
		template_names 	= "404.html"
		detail_comment = "El Artículo que deseas eliminar no existe"
		contextdata = {
			"detail_comment": detail_comment,
		}
		return render(request, template_names, contextdata, status = 404)
	# Verificamos que el autor sea el usuario
	if instance.author != request.user:
		template_name 	= "403.html"
		detail_comment = "Opsss!!!"
		content_text = instance.title
		contextdata = {
			"detail_comment": detail_comment,
			"userlogin": request.user,
			"content_text": content_text,
			"deleteall": True,
		}
		return render(request, template_name, contextdata, status = 403)
	# Elimina el articulo
	instance.delete()
	return redirect("articles:list")

ninjablog/views.py
# Django
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404

def homepage(request):
	template_name = 'homepage.html'
	context = {
	}
	return render(request, template_name, context)

def about(request):
	template_name = 'about.html'
	context = {
	}
	return render(request, template_name, context)

accounts/templates/login.html
{% extends "base.html" %}

{% block title %} USERS {% endblock %}

{% block content %}
	<div class="wrapper">
		<h1>Iniciar Sesión</h1>
		<div class="accounts">
			<form 
			action="{% url 'accounts:login' %}" 
			method="POST" 
			enctype="multipart/form-data"
			class="site-form">
				{% csrf_token %}
				{{ form.as_p }}
				{% if request.GET.next %}
				<input type="hidden" name="next" value="{{request.GET.next}}">
				{% endif%}
				<button class="site-buttom" type="submit">Iniciar Sesión</button>
			</form>
		</div>
		No estas registrado?
		<a href="{% url 'accounts:signup'%}">Registrate</a>
		<br>
		<a href="{% url 'home'%}">Regresar al Home</a>
	</div>
{% endblock content %}

accounts/templates/signup.html
{% extends "base.html" %}

{% block title %} USERS {% endblock %}

{% block content %}
	<div class="wrapper">
		<h1>Registrate</h1>
		<div class="accounts">
			<form action="" 
			method="POST" 
			enctype="multipart/form-data"
			class="site-form">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="site-buttom" type="submit">Registrar usuario</button>
			</form>
		</div>
		<a href="{% url 'home'%}">Regresar a la lista de Artículos</a>
	</div>
{% endblock content %}

articles/templates/article_create.html
{% extends "base.html" %}

{% block title %} ARTICLES {% endblock %}

{% block content %}
	<div class="wrapper">
		<div class="articles-create">
		<div>
		<h1> {{ title }} </h1>
		<a href="{% url 'articles:list'%}">Regresar a la lista de Artículos</a>
		</div>
			<form action="" method="POST" enctype="multipart/form-data" class="site-form">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="site-buttom" type="submit">Guardar</button>
			</form>
		</div>
	</div>
{% endblock content %}

articles/templates/article_detail.html
{% extends "base.html" %}

{% block title %} ARTICLES {% endblock %}

{% block content %}
	<div class="wrapper">
		<div class="article article-detail">
			<div class="article-header">
			{% if request.user == article.author %}
			<h1> 
				<a href="{% url 'articles:update' id=article.id %}"> {{ article.title }} </a> 
				<small class="enano"> <a href="{% url 'articles:delete' id=article.id %}"> Eliminar </a>  </small>
			</h1>
			{% else %}
			<h1> {{ article.title }} </h1>
			{% endif %}
			<img src="{{ article.Image.url }}">
			</div>
			<p style="text-align: justify;"> {{ article.body }} </p>
			<p style="color: grey;">Fecha de creación: {{ article.date }}</p>
			<p style="color: #3a8688;">Fecha de actualización: {{ article.updated }}</p>
			<p>Autor: {{ article.author.username }}</p>
		</div>
		<a href="{% url 'articles:list'%}">Regresar a la lista de Artículos</a>
	</div>
{% endblock content %}

articles/templates/article_list.html
{% extends "base.html" %}

{% block title %} ARTICLES {% endblock %}

{% block content %}
	<div class="wrapper">
		{% if request.user.is_authenticated %}
		<h1> <a href="{% url 'articles:create'%}">Lista de Artículos</a> </h1>
		{% else %}
		<h1> Lista de Artículos </h1>
		{% endif %}
		<div class="articles">
			{% for article in articles %}
			<div class="article">
			<h2> 
				<a href="{{ article.get_absolute_url }}"> {{ article.title }} </a> 
			</h2>
			<p style="color: grey;"> {{ article.snippet }} </p>
			<p style="color: grey;">Fecha de creación: {{ article.date }}</p>
			<p class="autor">Autor: {{ article.author.username }}</p>
			</div>
			{% endfor %}
		</div>
	</div>
{% endblock content %}

templates/about.html
{% extends "base.html" %}

{% block title %} ABOUT {% endblock %}

{% block content %}
	<div class="wrapper">
		<h1>About</h1>
		<p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
	</div>
{% endblock content %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Ninja-Blog{% endblock title %}</title>
	<!-- Estilos Extra -->
	<!-- Estilos propios -->
	<link rel="stylesheet" href="{% static 'css/estilos.css' %}">
	{% block head_extra %}{% endblock head_extra %}
</head>
<body>
	{% include 'navbar.html' %}	
	{% block content %}
	{% endblock %}
	<script type="text/javascript" src="{% static 'js/slugify.js' %}"></script>
</body>
</html>

templates/homepage.html
{% extends "base.html" %}

{% block title %} HOME {% endblock %}

{% block content %}
	<div class="wrapper">
		<h1>Home page</h1>
		<p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
	</div>
{% endblock content %}

templates/navbar.html
<nav class="navbar-ninja">
	<a class="nav-ninja ribbon" href="{% url 'home'%}">Home</a>
	<a class="nav-ninja ribbon" href="{% url 'about'%}">About</a>
	<a class="nav-ninja ribbon" href="{% url 'articles:list'%}">Articles</a>
	{% if request.user.is_superuser %}
	<a class="nav-ninja ribbon" href="{% url 'admin:index' %}">admin login</a>
	{% endif %}
	{% if not request.user.is_authenticated %}
	<a class="nav-ninja ribbon" href="{% url 'accounts:signup' %}">Registrate</a>
	<a class="nav-ninja ribbon" href="{% url 'accounts:login' %}">Iniciar Sesión</a>
	{% else %}
	<a class="nav-ninja ribbon" href="{% url 'accounts:logout' %}">Cerrar Sesión</a>
	<a class="nav-ninja ribbon" style="background-color: black;color: white; border-left: 15px solid transparent;"> {{ request.user|upper }} </a>
	{% endif %}
</nav>